---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.10
#  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[parkmap::default]
    attributes:
