name             'parkmap'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures parkmap'
long_description 'Installs/Configures parkmap'
version          '0.1.0'
depends          'git'
depends          'nodejs'
depends          'postgresql'
depends          'database'
depends          'xml'
depends          'nginx'
depends          'rbenv'