name             'parkmap'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures parkmap'
long_description 'Installs/Configures parkmap'
version          '0.1.0'
depends          'build-essential'
depends          'git'
depends          'postgresql'
depends          'database'
depends          'nodejs'
depends          'xml'
depends          'ruby_build'
depends          'rbenv'
depends          'nginx'
